// cryptope-api v0.0.1 35233f3afa7a12d729bc359bdc96c870f18b42aa
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/javascript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "35233f3afa7a12d729bc359bdc96c870f18b42aa"


//
// Types
//

export var TokenType;
(function (TokenType) {
  TokenType["USDC"] = "USDC"
  TokenType["DAI"] = "DAI"
})(TokenType || (TokenType = {}))

export class Version {
  constructor(_data) {
    this._data = {}
    if (_data) {
      this._data['webrpcVersion'] = _data['webrpcVersion']
      this._data['schemaVersion'] = _data['schemaVersion']
      this._data['schemaHash'] = _data['schemaHash']
      this._data['appVersion'] = _data['appVersion']
      
    }
  }
  get webrpcVersion() {
    return this._data['webrpcVersion']
  }
  set webrpcVersion(value) {
    this._data['webrpcVersion'] = value
  }
  get schemaVersion() {
    return this._data['schemaVersion']
  }
  set schemaVersion(value) {
    this._data['schemaVersion'] = value
  }
  get schemaHash() {
    return this._data['schemaHash']
  }
  set schemaHash(value) {
    this._data['schemaHash'] = value
  }
  get appVersion() {
    return this._data['appVersion']
  }
  set appVersion(value) {
    this._data['appVersion'] = value
  }
  
  toJSON() {
    return this._data
  }
}

export class Account {
  constructor(_data) {
    this._data = {}
    if (_data) {
      this._data['address'] = _data['address']
      this._data['name'] = _data['name']
      this._data['createdAt'] = _data['createdAt']
      this._data['email'] = _data['email']
      this._data['-'] = _data['-']
      
    }
  }
  get address() {
    return this._data['address']
  }
  set address(value) {
    this._data['address'] = value
  }
  get name() {
    return this._data['name']
  }
  set name(value) {
    this._data['name'] = value
  }
  get createdAt() {
    return this._data['createdAt']
  }
  set createdAt(value) {
    this._data['createdAt'] = value
  }
  get email() {
    return this._data['email']
  }
  set email(value) {
    this._data['email'] = value
  }
  get -() {
    return this._data['-']
  }
  set -(value) {
    this._data['-'] = value
  }
  
  toJSON() {
    return this._data
  }
}

export class Organization {
  constructor(_data) {
    this._data = {}
    if (_data) {
      this._data['id'] = _data['id']
      this._data['name'] = _data['name']
      this._data['createdAt'] = _data['createdAt']
      this._data['ownerAddress'] = _data['ownerAddress']
      this._data['token'] = _data['token']
      
    }
  }
  get id() {
    return this._data['id']
  }
  set id(value) {
    this._data['id'] = value
  }
  get name() {
    return this._data['name']
  }
  set name(value) {
    this._data['name'] = value
  }
  get createdAt() {
    return this._data['createdAt']
  }
  set createdAt(value) {
    this._data['createdAt'] = value
  }
  get ownerAddress() {
    return this._data['ownerAddress']
  }
  set ownerAddress(value) {
    this._data['ownerAddress'] = value
  }
  get token() {
    return this._data['token']
  }
  set token(value) {
    this._data['token'] = value
  }
  
  toJSON() {
    return this._data
  }
}

export class OrganizationMember {
  constructor(_data) {
    this._data = {}
    if (_data) {
      this._data['organizationID'] = _data['organizationID']
      this._data['memberAddress'] = _data['memberAddress']
      this._data['dateJoined'] = _data['dateJoined']
      this._data['role'] = _data['role']
      this._data['isAdmin'] = _data['isAdmin']
      this._data['salary'] = _data['salary']
      
    }
  }
  get organizationID() {
    return this._data['organizationID']
  }
  set organizationID(value) {
    this._data['organizationID'] = value
  }
  get memberAddress() {
    return this._data['memberAddress']
  }
  set memberAddress(value) {
    this._data['memberAddress'] = value
  }
  get dateJoined() {
    return this._data['dateJoined']
  }
  set dateJoined(value) {
    this._data['dateJoined'] = value
  }
  get role() {
    return this._data['role']
  }
  set role(value) {
    this._data['role'] = value
  }
  get isAdmin() {
    return this._data['isAdmin']
  }
  set isAdmin(value) {
    this._data['isAdmin'] = value
  }
  get salary() {
    return this._data['salary']
  }
  set salary(value) {
    this._data['salary'] = value
  }
  
  toJSON() {
    return this._data
  }
}

export class Payment {
  constructor(_data) {
    this._data = {}
    if (_data) {
      this._data['PaymentID'] = _data['PaymentID']
      this._data['OrganizationID'] = _data['OrganizationID']
      this._data['memberAddress'] = _data['memberAddress']
      this._data['transactionHash'] = _data['transactionHash']
      this._data['amount'] = _data['amount']
      this._data['token'] = _data['token']
      this._data['date'] = _data['date']
      
    }
  }
  get PaymentID() {
    return this._data['PaymentID']
  }
  set PaymentID(value) {
    this._data['PaymentID'] = value
  }
  get OrganizationID() {
    return this._data['OrganizationID']
  }
  set OrganizationID(value) {
    this._data['OrganizationID'] = value
  }
  get memberAddress() {
    return this._data['memberAddress']
  }
  set memberAddress(value) {
    this._data['memberAddress'] = value
  }
  get transactionHash() {
    return this._data['transactionHash']
  }
  set transactionHash(value) {
    this._data['transactionHash'] = value
  }
  get amount() {
    return this._data['amount']
  }
  set amount(value) {
    this._data['amount'] = value
  }
  get token() {
    return this._data['token']
  }
  set token(value) {
    this._data['token'] = value
  }
  get date() {
    return this._data['date']
  }
  set date(value) {
    this._data['date'] = value
  }
  
  toJSON() {
    return this._data
  }
}

  
//
// Client
//

export class API {
  constructor(hostname, fetch) {
    this.path = '/rpc/API/'
    this.hostname = hostname
    this.fetch = fetch
  }

  url(name) {
    return this.hostname + this.path + name
  }
  
  ping = (headers) => {
    return this.fetch(
      this.url('Ping'),
      createHTTPRequest({}, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: (_data.status)
        }
      })
    })
  }
  
  version = (headers) => {
    return this.fetch(
      this.url('Version'),
      createHTTPRequest({}, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          version: new Version(_data.version)
        }
      })
    })
  }
  
}

  
const createHTTPRequest = (body = {}, headers = {}) => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res) => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status }
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}
