// Code generated by sqlc. DO NOT EDIT.
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one

INSERT INTO accounts(address, name, email, admin)
VALUES ($1, $2, $3, $3)
RETURNING address, name, created_at, email, admin
`

type CreateUserParams struct {
	Address []byte      `json:"address"`
	Name    string      `json:"name"`
	Email   interface{} `json:"email"`
}

// address	bytea
// name	character varying(60)
// created_at	timestamp NULL [now()]
// email	domain_email
// admin	boolean NULL [false]
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Accounts, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Address, arg.Name, arg.Email)
	var i Accounts
	err := row.Scan(
		&i.Address,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Admin,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM accounts
WHERE address = $1
`

func (q *Queries) DeleteUser(ctx context.Context, address []byte) error {
	_, err := q.db.ExecContext(ctx, deleteUser, address)
	return err
}

const getUser = `-- name: GetUser :one
SELECT address, name, created_at, email, admin FROM accounts WHERE address = $1
`

func (q *Queries) GetUser(ctx context.Context, address []byte) (Accounts, error) {
	row := q.db.QueryRowContext(ctx, getUser, address)
	var i Accounts
	err := row.Scan(
		&i.Address,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Admin,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE accounts 
SET
  name = $2,
  email = $3,
  admin = $4
WHERE address = $1
RETURNING address, name, created_at, email, admin
`

type UpdateUserParams struct {
	Address []byte       `json:"address"`
	Name    string       `json:"name"`
	Email   interface{}  `json:"email"`
	Admin   sql.NullBool `json:"admin"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Accounts, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Address,
		arg.Name,
		arg.Email,
		arg.Admin,
	)
	var i Accounts
	err := row.Scan(
		&i.Address,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Admin,
	)
	return i, err
}
